user: git
group: git
services:
  - postgres
before_precompile: ./bin/pkgr_before_precompile.sh
installer: true
services:
  - postgres
wizards:
  - https://github.com/pkgr/addon-mysql.git
  - https://github.com/pkgr/addon-apache2.git
  - https://github.com/pkgr/addon-redis.git
  - https://github.com/pkgr/addon-smtp.git
  - https://github.com/pkgr/addon-gitlabhq.git
targets:
  debian-7: &wheezy
    build_dependencies:
      - libkrb5-dev
      - libicu-dev
      - cmake
      - pkg-config
    dependencies:
      - libicu48
      - libpcre3
      - git
  debian-8: *wheezy
  ubuntu-14.04:
    build_dependencies:
      - libkrb5-dev
      - libicu-dev
      - cmake
      - pkg-config
    dependencies:
      - libicu52
      - libpcre3
      - git
  centos-6:
    build_dependencies:
      - krb5-devel
      - libicu-devel
      - cmake
      - pkgconfig
    dependencies:
      - libicu
      - pcre
      - git
